name: redux_persist
description: Persist Redux State
version: 0.0.2
homepage: https://github.com/Cretezy/redux_persist
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^2.1.1
  path_provider: ^0.3.1

dev_dependencies:
  test: ^0.12.0
  flutter_redux: ^0.3.5
